[build]
  publish = "build"

[[redirects]]
  from = "/app/results"
  to = "/app/results.html"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/app/results.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200